# Site settings
title: Peter Slavin
name: Peter Slavin

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Email
   url: mailto:pbslavin@gmail.com
 - title: GitHub
   url: https://github.com/pbslavin
 - title: LinkedIn
   url: http://www.linkedin.com/in/peter-slavin-46824790

#Any buzzword skills you want to include
skills:
 - C#/ASP.NET Core
 - JavaScript
 - HTML/CSS
 - Node.js
 - React
 - Redux
 - MS SQL Server
 - REST
 - Git/GitHub
 - Docker
 - xUnit
 - Selenium
 - design patterns
 - Linux

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
# blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Junior developer
   start: 2019
   end: Ongoing
   description: Building an investor data management application, working under lead developer Matt Cameron, for private investment company Canaras Capital Management, LLC, in React and C#. <a href="https://www.canaras.com" target="_blank">canaras.com</a>
 - title: Textbook editor
   start: 2018
   end: 2019
   employer: Austin Coding Academy
   description: Wrote and edited instructional texts. <a href="https://www.austincodingacademy.com" target="_blank">austincodingacademy.com</a>
 - title: Pianist
   start: 2018
   end: 2019
   employer: St Helen Catholic Church
   description: Georgetown, TX. <a href="https://www.sainthelens.org" target="_blank">sainthelens.org</a>
 - title: Piano Instructor
   start: 2018
   end: 2019
   employer: Pfluger-Rock School of Music
   description: Pflugerville, TX. <a href="https://www.austinacademyofmusic.com/pfluger-rock/" target="_blank">austinacademyofmusic.com/pfluger-rock/</a>
#  - title: Accompanist
#    start: 2014
#    end: 2018
#    employer: Trinity Presbyterian Church
#    description: San Carlos, CA. <a href="https://www.trinity-pres.org" target="_blank">trinity-pres.org</a>
#  - title: Quality Control Specialist
#    start: 2008
#    end: 2012
#    employer: Nan McKay and Associates
#    description: Caught housing subsidy errors and helped developed tools for this purpose, ensuring continuation of Federal and local funding, and retention of the contract for the Chicago, IL Housing Authority

#Education is required
education:
 - level: Certificate
   date: 2018
   subject: C#/.NET Full-Stack Web Development
   school: Austin Coding Academy
   website: <a href="https://www.austincodingacademy.com" taget="_blank">austincodingacademy.com</a>
 - level: Doctor of Philosophy (PhD)
   date: 2004
   subject: Music
   school: UC Berkeley
   website: <a href="https://www.berkeley.edu" taget="_blank">berkeley.edu</a>
 - level: Diploma
   date: 1997
   subject: C/COBOL/CICS Programming and Networking
   website: (School now defunct)
   school: Computer Learning Center
 - level: Bachelor of Music (BM)
   date: 1990
   subject: Composition
   school: San Francisco Conservatory of Music
   website: <a href="https://www.sfcm.edu" taget="_blank">sfcm.edu</a>

#This section is optional (as is the image link below)
# coursera:
#    profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#    courses:
#     - title: Functional Programming Principles in Scala
#       link: https://www.coursera.org/course/progfun
#       optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#       date: September 16, 2013
#     - title: Algorithms Design and Analysis, Part 1
#       link: https://www.coursera.org/specializations/algorithms
#       optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#       date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
# speakerdeck:
#    profileurl: https://speakerdeck.com/robhinds
#    talks:
#     - title: Product Management for Engineers
#       speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#       conference: API Conference, Berlin 2018
#     - title: Agile Machine Learning - from Theory to Production
#       speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#       conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
# github:
#  - robhinds/robhinds.github.io
#  - robhinds/ScaLambda
#  - robhinds/opinionated-akka-http
#  - robhinds/food2vec
#  - robhinds/microservices
#  - robhinds/spring-social-geeklist
#  - robhinds/spring-social-stackoverflow
#  - robhinds/genotype
#  - robhinds/footweets
#  - robhinds/ElasticSearchGradle

#Stackoverflow flair is optional
# stackoverflow:
#    profileurl: http://stackoverflow.com/users/258813/rhinds
#    flairimageurl: http://stackoverflow.com/users/flair/258813.png

intro: |
  I am a lifelong musician, and have worked as a pianist and teacher all my adult life. My interest in software development arose in the 1990s, and has more recently become my focus professionally. I am a graduate of Austin Coding Academy's .NET full-stack developer program, after which I worked for the school in writing and editing its .NET, JavaScript and WordPress textbooks and course materials. I am currently working as a junior developer under an independent lead, building an investment data management system in React and C#. <br/><br/>
  I have built applications, mostly for myself, using technologies and languages, from C to the MEAN stack. My current areas of focus are React/Redux and ASP.NET Core. I am fanatical about writing clean and efficient code, and delivering it on time.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
# additionalinfo: |
#    <strong>Scala</strong>: My current role uses Scala as the primary language and have been building applications in Scala for the last two years. I am familiar with a range of Scala libraries, such as <a target="_blank" href="http://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Akka-Http for building microservices</a> and <a target="_blank" href="http://automateddeveloper.blogspot.com/2018/09/generic-programming-with-scala.html"> Shapeless for generic programming</a>, as well as familiar with a range of <a target="_blank" href="https://basementcrowd.com/2018/11/28/scala-the-aux-pattern-path-dependent-types/" >functional programming techniques available</a>.<br/><br/>
#    <strong>Java</strong>: I am experienced in a variety of Java APIâ€™s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
#    <strong>Groovy</strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
#    <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="http://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="http://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
#    <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
#    <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
#    I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
#    As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="http://projects.spring.io/spring-social/">http://projects.spring.io/spring-social/</a>. <br/><br/>
#    I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="http://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
